server:
  port: 8888


#应用名称
spring:
  application:
    name: dcloud-gateway

  #服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: 118.89.95.131:8848
        username: nacos
        password: nacos


